import assert from 'node:assert/strict';
import { collect, fingerprint, menuWeekStart } from '../scripts/menu-snapshot';
import { calendar, restaurants } from '../lib/menus';
const now=new Date('2026-09-18T10:00:00Z');
const menuHtml='<h2>Vecka 38</h2><h3>Måndag</h3><p>Rätt A</p><h3>Tisdag</h3><p>Rätt B</p><h3>Onsdag</h3><p>Rätt C</p><h3>Torsdag</h3><p>Rätt D</p><h3>Fredag</h3><p>Rätt E</p><h3>Frukost:</h3>';
const fetcher=(async()=>new Response(menuHtml)) as typeof fetch;
const first=await collect(undefined,fetcher,now);
assert.equal(first.menus.length,7);
assert.equal(first.menus.find(m=>m.id==='mickes')?.days[0][0],'Rätt A');
assert.ok(first.menus.find(m=>m.id==='matverkstan')?.error);
const later=new Date('2026-09-18T12:00:00Z');
const same=await collect(first,fetcher,later);assert.equal(fingerprint(first),fingerprint(same),'Timestamp-only changes must not republish');
const failed=await collect(first,(async()=>new Response('',{status:503})) as typeof fetch,later);
const old=failed.menus.find(m=>m.id==='mickes')!;
assert.equal(old.days[0][0],'Rätt A');assert.equal(old.checkedAt,now.toISOString());assert.equal(old.attemptedAt,later.toISOString());assert.equal(old.fetchFailed,true);assert.notEqual(fingerprint(failed),fingerprint(first));
const recovered=await collect(failed,fetcher,later);assert.equal(recovered.menus.find(m=>m.id==='mickes')?.fetchFailed,false);
const broken=await collect(first,(async()=>new Response('<html>Site maintenance</html>')) as typeof fetch,later);assert.equal(broken.menus.find(m=>m.id==='mickes')?.days[0][0],'Rätt A');
assert.equal(menuWeekStart(38,now),'2026-09-14');assert.equal(menuWeekStart(53,new Date('2027-01-04T12:00:00Z')),'2026-12-28');
assert.equal(calendar(new Date('2026-09-20T22:30:00Z')).week,39);
assert.equal(new Set(restaurants.map(r=>r.id)).size,7);
console.log('PASS: collection, independent source errors, retained menus, recovery, change detection and week/year boundaries.');
