"use client";
import { useEffect, useState } from "react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Utensils, ArrowUpRight, RefreshCw, MapPin, CalendarDays, CircleCheck } from "lucide-react";
import { restaurants, weekdays, calendar, type Menu } from "@/lib/menus";
export default function Home({staticDataUrl}:{staticDataUrl?:string}={}) {
 const [menus,setMenus]=useState<Menu[]>([]),[day,setDay]=useState("0"),[date,setDate]=useState<ReturnType<typeof calendar>|null>(null),[busy,setBusy]=useState(true),[failed,setFailed]=useState(false);
 async function load(){setBusy(true);setFailed(false);try{const r=await fetch(staticDataUrl??'/api/menus',{cache:'no-store'});if(!r.ok)throw Error();const data=await r.json() as {menus:Menu[]};setMenus(data.menus);setDate(calendar());}catch{setFailed(true);}finally{setBusy(false);}}
 useEffect(()=>{const c=calendar();setDate(c);setDay(String(Math.min(c.day,4)));load();const t=setInterval(load,15*60*1000);return()=>clearInterval(t);},[]);
 const current=menus.filter(m=>!m.error&&m.week===date?.week&&(!m.weekStart||m.weekStart===date?.weekStart)).length;
 return <main><header className="topbar"><a className="brand" href="./"><span className="brandmark"><Utensils size={21}/></span>lunchkollen<span className="branddot">.</span></a><span className="place"><MapPin size={15}/>Linköping</span></header>
 <section className="intro"><div><p className="eyebrow">GOD MAT. ENKLARE LUNCHVAL.</p><h1>Vad blir det till <em>lunch?</em></h1><p className="lead">{restaurants.length} restauranger. Hela veckan. Allt på ett ställe.</p></div><div className="weekstamp"><CalendarDays size={23}/><div><span>VECKANS MENYER</span><strong>Vecka {date?.week??'–'}</strong><small>{date?.range??'Måndag – fredag'}</small></div></div></section>
 <Tabs value={day} onValueChange={setDay}><div className="weekbar"><TabsList aria-label="Välj lunchdag" className="days">{weekdays.map((d,i)=><TabsTrigger key={d} value={String(i)} className="day">{d}<span>{date?.dates[i]} {date?.day===i&&<b>idag</b>}</span></TabsTrigger>)}</TabsList><button className="refresh" onClick={load} disabled={busy} aria-label="Läs senaste publicerade menyer"><RefreshCw size={17} className={busy?'spin':''}/><span>{busy?'Hämtar…':'Läs senaste menyer'}</span></button></div>
 <div className="statusline" aria-live="polite"><span><span className="dot"/>{busy?'Läser senaste menyerna':failed?'Kunde inte hämta menyer. Försök igen.':`${current} av ${restaurants.length} menyer för vecka ${date?.week}`}</span><span>Uppdateras automatiskt</span></div>
 {weekdays.map((d,i)=><TabsContent value={String(i)} key={d}><div className="cards">{restaurants.map((r,index)=>{const m=menus.find(x=>x.id===r.id),fresh=m?.week===date?.week&&(!m?.weekStart||m.weekStart===date?.weekStart),dishes=m?.days[i]??[],priceNote=m?.price?[m.priceFetchFailed?'Senast bekräftat':null,m.price.note].filter(Boolean).join(' · '):'';return <article key={r.id} className="restaurant"><div className="cardtop"><span className={`initial initial-${index}`}>{r.mark}</span><div><h2>{r.name}</h2><p>{r.subtitle}</p></div><a href={r.url} target="_blank" rel="noreferrer" className="external" aria-label={`Besök ${r.name}`}><ArrowUpRight size={20}/></a></div>{m?.price&&<div className={`priceinfo${m.priceFetchFailed?' price-old':''}`}><strong>Lunch {m.price.amount} kr</strong>{priceNote&&<span>{priceNote}</span>}</div>}<div className="menulabel"><span>{d.toUpperCase()}</span><span className={!fresh&&m?'old':''}>{m?.week?`V. ${m.week}${!fresh?' · annan vecka':''}`:'VECKOMENY'}</span></div>
 {!m?<p className="empty">{busy?'Menyn hämtas…':'Menyn kunde inte hämtas.'}</p>:m.error?<p className="empty">Menyn kunde inte läsas just nu. Se restaurangens egen meny.</p>:<>{m.fetchFailed&&<p className="notice">Senaste hämtningen misslyckades. Här visas senast sparade meny.</p>}{!fresh&&<p className="notice">Restaurangens senaste meny gäller vecka {m.week}. Veckans meny är inte bekräftad.</p>}{dishes.length?<ul className="dishes">{dishes.map((dish,j)=><li key={j}>{dish}</li>)}</ul>:<p className="empty">Ingen meny publicerad för {d.toLowerCase()}.</p>}{m.weekly.length>0&&<details><summary>Finns också hela veckan <span>+</span></summary><ul>{m.weekly.map((dish,j)=><li key={j}>{dish}</li>)}</ul></details>}</>}
 <footer className="cardfoot"><span>{m?.checkedAt?`Hämtad ${new Date(m.checkedAt).toLocaleString('sv-SE',{timeZone:'Europe/Stockholm',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}`:'Direkt från restaurangen'}</span><a href={r.url} target="_blank" rel="noreferrer">Originalmeny <ArrowUpRight size={14}/></a></footer></article>;})}</div></TabsContent>)}</Tabs>
 <aside className="update-note"><CircleCheck size={21}/><div><strong>En ny vecka, nya luncher.</strong><p>{staticDataUrl?'Menyer och priser kontrolleras automatiskt på måndagsmorgnar. Sidan publiceras på nytt när något ändras. Knappen läser den senaste publicerade versionen.':'Menyerna kontrolleras när du öppnar sidan och var 15:e minut medan den är öppen.'}</p></div></aside><footer className="bottom"><span>lunchkollen<span className="branddot">.</span> <span className="muted">Linköping</span></span><p>Menyer och priser kommer från restaurangernas egna hemsidor. Med reservation för ändringar.</p></footer></main>;
}
